// 성경 66권 메타데이터
// chapters: 장 수, verses: 총 절 수(개역개정 기준)
// verses 는 "하루에 읽는 실제 분량"을 균등하게 맞추는 데만 쓰인다.
export const BOOKS = [
  // ── 구약 ──────────────────────────────────────────────
  { name: '창세기',       chapters: 50,  verses: 1533, testament: 'old' },
  { name: '출애굽기',     chapters: 40,  verses: 1213, testament: 'old' },
  { name: '레위기',       chapters: 27,  verses: 859,  testament: 'old' },
  { name: '민수기',       chapters: 36,  verses: 1288, testament: 'old' },
  { name: '신명기',       chapters: 34,  verses: 959,  testament: 'old' },
  { name: '여호수아',     chapters: 24,  verses: 658,  testament: 'old' },
  { name: '사사기',       chapters: 21,  verses: 618,  testament: 'old' },
  { name: '룻기',         chapters: 4,   verses: 85,   testament: 'old' },
  { name: '사무엘상',     chapters: 31,  verses: 810,  testament: 'old' },
  { name: '사무엘하',     chapters: 24,  verses: 695,  testament: 'old' },
  { name: '열왕기상',     chapters: 22,  verses: 816,  testament: 'old' },
  { name: '열왕기하',     chapters: 25,  verses: 719,  testament: 'old' },
  { name: '역대상',       chapters: 29,  verses: 942,  testament: 'old' },
  { name: '역대하',       chapters: 36,  verses: 822,  testament: 'old' },
  { name: '에스라',       chapters: 10,  verses: 280,  testament: 'old' },
  { name: '느헤미야',     chapters: 13,  verses: 406,  testament: 'old' },
  { name: '에스더',       chapters: 10,  verses: 167,  testament: 'old' },
  { name: '욥기',         chapters: 42,  verses: 1070, testament: 'old' },
  { name: '시편',         chapters: 150, verses: 2461, testament: 'old' },
  { name: '잠언',         chapters: 31,  verses: 915,  testament: 'old' },
  { name: '전도서',       chapters: 12,  verses: 222,  testament: 'old' },
  { name: '아가',         chapters: 8,   verses: 117,  testament: 'old' },
  { name: '이사야',       chapters: 66,  verses: 1292, testament: 'old' },
  { name: '예레미야',     chapters: 52,  verses: 1364, testament: 'old' },
  { name: '예레미야애가', chapters: 5,   verses: 154,  testament: 'old' },
  { name: '에스겔',       chapters: 48,  verses: 1273, testament: 'old' },
  { name: '다니엘',       chapters: 12,  verses: 357,  testament: 'old' },
  { name: '호세아',       chapters: 14,  verses: 197,  testament: 'old' },
  { name: '요엘',         chapters: 3,   verses: 73,   testament: 'old' },
  { name: '아모스',       chapters: 9,   verses: 146,  testament: 'old' },
  { name: '오바댜',       chapters: 1,   verses: 21,   testament: 'old' },
  { name: '요나',         chapters: 4,   verses: 48,   testament: 'old' },
  { name: '미가',         chapters: 7,   verses: 105,  testament: 'old' },
  { name: '나훔',         chapters: 3,   verses: 47,   testament: 'old' },
  { name: '하박국',       chapters: 3,   verses: 56,   testament: 'old' },
  { name: '스바냐',       chapters: 3,   verses: 53,   testament: 'old' },
  { name: '학개',         chapters: 2,   verses: 38,   testament: 'old' },
  { name: '스가랴',       chapters: 14,  verses: 211,  testament: 'old' },
  { name: '말라기',       chapters: 4,   verses: 55,   testament: 'old' },
  // ── 신약 ──────────────────────────────────────────────
  { name: '마태복음',         chapters: 28, verses: 1071, testament: 'new' },
  { name: '마가복음',         chapters: 16, verses: 678,  testament: 'new' },
  { name: '누가복음',         chapters: 24, verses: 1151, testament: 'new' },
  { name: '요한복음',         chapters: 21, verses: 879,  testament: 'new' },
  { name: '사도행전',         chapters: 28, verses: 1007, testament: 'new' },
  { name: '로마서',           chapters: 16, verses: 433,  testament: 'new' },
  { name: '고린도전서',       chapters: 16, verses: 437,  testament: 'new' },
  { name: '고린도후서',       chapters: 13, verses: 257,  testament: 'new' },
  { name: '갈라디아서',       chapters: 6,  verses: 149,  testament: 'new' },
  { name: '에베소서',         chapters: 6,  verses: 155,  testament: 'new' },
  { name: '빌립보서',         chapters: 4,  verses: 104,  testament: 'new' },
  { name: '골로새서',         chapters: 4,  verses: 95,   testament: 'new' },
  { name: '데살로니가전서',   chapters: 5,  verses: 89,   testament: 'new' },
  { name: '데살로니가후서',   chapters: 3,  verses: 47,   testament: 'new' },
  { name: '디모데전서',       chapters: 6,  verses: 113,  testament: 'new' },
  { name: '디모데후서',       chapters: 4,  verses: 83,   testament: 'new' },
  { name: '디도서',           chapters: 3,  verses: 46,   testament: 'new' },
  { name: '빌레몬서',         chapters: 1,  verses: 25,   testament: 'new' },
  { name: '히브리서',         chapters: 13, verses: 303,  testament: 'new' },
  { name: '야고보서',         chapters: 5,  verses: 108,  testament: 'new' },
  { name: '베드로전서',       chapters: 5,  verses: 105,  testament: 'new' },
  { name: '베드로후서',       chapters: 3,  verses: 61,   testament: 'new' },
  { name: '요한일서',         chapters: 5,  verses: 105,  testament: 'new' },
  { name: '요한이서',         chapters: 1,  verses: 13,   testament: 'new' },
  { name: '요한삼서',         chapters: 1,  verses: 15,   testament: 'new' },
  { name: '유다서',           chapters: 1,  verses: 25,   testament: 'new' },
  { name: '요한계시록',       chapters: 22, verses: 404,  testament: 'new' },
];

export const TOTAL_CHAPTERS = BOOKS.reduce((s, b) => s + b.chapters, 0); // 1189
export const TOTAL_VERSES   = BOOKS.reduce((s, b) => s + b.verses, 0);   // 31103
